language: node_js
install: travis_wait 30 mvn install
script: 
  - make build files run-node
notifications:
  email:
    recipients:
      - ademin@gmail.com
    on_success: always
    on_failure: always
